name: Docker conatiner
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    env: 
      SHA: ${GITHUB_SHA}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vinodn13/python:${{github.sha}} 
      - name: EXECUTE DOCKER COMMAND 
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }} 
          username: ubuntu 
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }} 
          command: sudo docker service ls
          #command: sudo docker service update --replicas 1 --image vinodn13/python:${{github.sha}} pyt_new

